feat: add backToTop button
MaaAssistantArknights/maa-copilot-frontend pull request #121
Opened 2023-02-01 09:29 UTC by FutabaRio

re #76

2023-02-02 02:34 UTC, guansss requested changes

2023-02-02 02:34 UTC, guansss commented on src/components/BackToTop.tsx
> +  }, [])
需要在 unmount 时移除监听，不然会造成内存泄漏

2023-02-02 10:24 UTC, FutabaRio commented on src/components/BackToTop.tsx
> +  }, [])
佬 加上了 unmount 在看看

2023-02-03 01:58 UTC, guansss approved these changes
![approved](https://user-images.githubusercontent.com/46285865/202906742-30d61d71-044b-43b9-b216-232532202acc.png)

2023-02-03 01:59 UTC, merged

2023-04-27 02:41 UTC, Wanniki commented
每次鼠标 滚动 都会执行 document.getElementById('container').scrollTop 来查询元素的 scrollTop 属性，可以不用使用 useRef 直接获取到 DOM 元素的引用，避免了查询操作，可以提高性能。
滚动条的的高频率触发，在一些特定的时机会不会有性能问题。