Guan/temp1 #52方案
MaaAssistantArknights/maa-copilot-frontend pull request #252
Opened 2024-02-03 15:59 UTC by Gemini2035

> 新增/create侧边框快速编辑模块，实现功能：

1. 干员的CRUD
2. 干员组的CRUD
3. 基于已选择干员的职业分支提供推荐分组
4. 收藏干员组（数据存本地，按用户id分类）
5. 从wiki上下载职业图标，但分支图标效果不好，职业图标更是一团遭，其实可以考虑放弃职业图标用bp的icon代替，至少风格统一（

> 改动较大，但这次有信心（

2024-02-04 09:38 UTC, guansss commented
还没有看代码，这里是使用体验上一些也许可以改进的地方（

1. 可以让右栏的职业只显示图标，左栏的分支只显示文字，因为职业图标辨识度很高，而且游戏里也是这么显示的，而对于分支来说是文字辨识度比较高
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/46285865/77e4e9eb-e6a8-4ec2-85f4-cae1347fad2d)

2. 收藏分组最好允许直接在列表里删除，比较符合直觉

3. 干员列表建议改为竖向滚动，因为在网页上竖向滚动会比较自然，而且用 js 模拟滚动的体验比不上浏览器自带的平滑滚动

4. 干员组卡片是 interactive 的，但是点击后并没有对应的功能，可以改为点击后展开/折叠，或者去掉 interactive
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/46285865/f6a567f9-1edc-4c16-82d1-e1d9f9379142)

6. “未设置技能”建议只显示在已选择的干员上，这样整个列表会比较简洁
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/46285865/607661fc-d01e-4b30-8f0c-e889d1fe17f5)

7. “分组”需要改为“干员组”
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/46285865/208c0bfd-a72e-4a28-aa6b-fbcb0a68331f)

2024-02-07 09:54 UTC, Gemini2035 commented
更新完毕，除开提到过的六个修改点之外的主要修改点：

1. 简化sheet的页面滚动，简单来说就是最多只看得到两个滚动条（
2. 修复了收藏干员组表现不稳定的bug，原因为组件未正确更新（useMemo一把梭，结果梭出问题了
3. 优化了干员全选功能
4. 可能存在风险的点：sheet部分功能几乎是独立的，但是使用了EditorPerformer.tsx中封装好了的submitOperator、submitGroup函数。为了同时适配两个部分，添加了fromSheet参数，并把setError改为了可选。自测了一下没有发现问题

2024-02-07 11:01 UTC, guansss requested changes
职业图标好像没有提交？

`useMemo` 用得有点过多了……这样会导致 html 结构不明显，比较影响写 css 的体验，而且没有处理好 deps 的话会出现很多 bug，比如我标出来的这段代码（也许还有其他地方，没仔细看）

所以建议只在有必要的时候再使用 `useMemo`，并且在使用时仔细检查一下 deps，或者装上 eslint-plugin-react-hooks 来自动检查

2024-02-07 11:13 UTC, Gemini2035 commented on src/components/editor/operator/sheet/sheetGroup/SheetGroupItem.tsx
> +  )
确实存在这个情况，useMemo 滥用了，今晚修改。
职业图标可以跑一下script文件夹的脚本，我也会在下次上传时附上

2024-02-07 14:54 UTC, Gemini2035 commented on src/components/editor/operator/sheet/sheetGroup/SheetGroupItem.tsx
> +  )
已减少useMemo的使用，同时上传了职业图标

2024-02-08 07:15 UTC, guansss requested changes
提出了一些建议，很多都是关于 useMemo 的，所以说 useMemo 真是万恶之源啊（

此外，代码里有很多把事件监听器传入 props 的用法（`eventHandleProxy`），感觉这种模式不适合用在 react 上，既然已经可以把 `onXXX` `onYYY` 传入 props 来实现监听，就没有必要再把 `XXX` `YYY` 封装成一个事件监听器了，毕竟监听器的执行流程不清晰，阅读/调试起来会很痛苦，另外，就算要用也得处理好类型，一般来说都需要把事件参数用~~类型体操~~泛型来定义，不然会丢失类型安全性

2024-02-08 07:15 UTC, guansss commented on src/components/editor/operator/sheet/SheetOperator.tsx
> +  )
缺少 `existedOperators` 依赖

2024-02-08 07:15 UTC, guansss commented on src/components/editor/operator/sheet/SheetOperatorSkillAbout.tsx
> +  }, [])
常量应该放到组件外面，而且这里的 `map()` 好像并没有起什么作用

2024-02-18 10:53 UTC, guansss requested changes
新年快乐啊！过完年该开始搬砖力（

我之前说的事件监听器其实不太准确，应该说是“监听多个事件”的事件监听器，比如现在的写法是下面这样，把 `X` 和 `Y` 事件放在同一个监听器里

```jsx
enum EventType {
  X,
  Y,
}

const eventHandleProxy = (event: EventType) => {
  switch (event) {
    case EventType.X:
      doX()
      break
    case EventType.Y:
      doY()
      break
  }
}

<Component eventHandleProxy={eventHandleProxy} />
```

React 里一般像下面这么写，虽然传的 prop 更多，但代码更清晰，而且要优化的话可以给每个函数按需套上 `useCallback`

```jsx
const handleX = () => {
  doX()
}

const handleY = () => {
  doY()
}

<Component onX={handleX} onY={handleY} />
```

此外，eventHandleProxy 并不符合 reducer 模式，因为 reducer 要和 state 绑定，也就是用 reducer 来封装对 state 的所有操作，好处是让 state 的变化可以预测，而 eventHandleProxy 操作的 state 是从组件外面传进来的，导致无法封装所有操作，state 的变化不可预测

所以 eventHandleProxy 无法享受 reducer 模式的好处，反而承受其坏处：

- 违背单一职责原则，一个函数做了太多事情
- 增加代码复杂度，影响可读性
- 可扩展性不好，以后如果要对某个 event 做一些修改，比如增加参数或返回值的话，需要用泛型，进一步增加复杂度

……说了这么多但其实问题不大，不改也行，之前过于挑剔了（

其他有几个容易出 bug 的小问题，需要改一改

另外，感觉不是很有必要根据用户 ID 来区分 fav group？毕竟同一台电脑多个账号的可能性不大，而且 fav group 也不算是隐私数据，其他保存在本地的状态都是没有区分用户 ID 的

2024-02-18 16:56 UTC, Gemini2035 commented
> 嗯嗯，理解到了。不过暂时只改了后面的及格问题。eventProxyHandle后续慢慢会改（会改的！~确信~）

本来摆了，结果写上头了，最后还是把eventProxyHandle拆成单个单个的功能函数了（

2024-02-19 10:48 UTC, guansss commented
Nice work! 感谢贡献，我拉下来合并一下

2024-02-19 11:30 UTC, merged